//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponBuddy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouponBuddy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://couponbuddy.azurewebsites.net/.
        /// </summary>
        internal static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons@pg-technologies.com.
        /// </summary>
        internal static string EMAIL_FROM {
            get {
                return ResourceManager.GetString("EMAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.pg-technologies.com.
        /// </summary>
        internal static string EMAIL_HOST {
            get {
                return ResourceManager.GetString("EMAIL_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane10.
        /// </summary>
        internal static string EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons@pg-technologies.com.
        /// </summary>
        internal static string EMAIL_USER {
            get {
                return ResourceManager.GetString("EMAIL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string INACTIVE_AD_DURATION {
            get {
                return ResourceManager.GetString("INACTIVE_AD_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string INACTIVITY_TIMEOUT {
            get {
                return ResourceManager.GetString("INACTIVITY_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62885dd9-0d90-420e-9141-ecbbd8ed5c62.
        /// </summary>
        internal static string LOCATION_ID {
            get {
                return ResourceManager.GetString("LOCATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +19124809477.
        /// </summary>
        internal static string TEXT_ACCOUNT_FROM {
            get {
                return ResourceManager.GetString("TEXT_ACCOUNT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACb758ac931310f20c39f7e0d7451ae3b4.
        /// </summary>
        internal static string TEXT_ACCOUNT_SID {
            get {
                return ResourceManager.GetString("TEXT_ACCOUNT_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 523ab04082e6a42db840cc39b3b7d242.
        /// </summary>
        internal static string TEXT_ACCOUNT_TOKEN {
            get {
                return ResourceManager.GetString("TEXT_ACCOUNT_TOKEN", resourceCulture);
            }
        }
    }
}
